---
galaxy_info:
  role_name: shell
  author: Adrien Bouchardon
  description: "Shell interactif : zsh/bash, alias et invite de commande"
  license: AGPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - workstation
    - configuration

dependencies: []
