---
galaxy_info:
  role_name: dev
  author: Adrien Bouchardon
  description: "Outillage de développement : langages, build et conteneurs"
  license: AGPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - workstation
    - configuration

dependencies: []
